require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WalkthroughsController do

  # This should return the minimal set of attributes required to create a valid
  # Walkthrough. As you add validations to Walkthrough, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WalkthroughsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all walkthroughs as @walkthroughs" do
      walkthrough = Walkthrough.create! valid_attributes
      get :index, {}, valid_session
      assigns(:walkthroughs).should eq([walkthrough])
    end
  end

  describe "GET show" do
    it "assigns the requested walkthrough as @walkthrough" do
      walkthrough = Walkthrough.create! valid_attributes
      get :show, {:id => walkthrough.to_param}, valid_session
      assigns(:walkthrough).should eq(walkthrough)
    end
  end

  describe "GET new" do
    it "assigns a new walkthrough as @walkthrough" do
      get :new, {}, valid_session
      assigns(:walkthrough).should be_a_new(Walkthrough)
    end
  end

  describe "GET edit" do
    it "assigns the requested walkthrough as @walkthrough" do
      walkthrough = Walkthrough.create! valid_attributes
      get :edit, {:id => walkthrough.to_param}, valid_session
      assigns(:walkthrough).should eq(walkthrough)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Walkthrough" do
        expect {
          post :create, {:walkthrough => valid_attributes}, valid_session
        }.to change(Walkthrough, :count).by(1)
      end

      it "assigns a newly created walkthrough as @walkthrough" do
        post :create, {:walkthrough => valid_attributes}, valid_session
        assigns(:walkthrough).should be_a(Walkthrough)
        assigns(:walkthrough).should be_persisted
      end

      it "redirects to the created walkthrough" do
        post :create, {:walkthrough => valid_attributes}, valid_session
        response.should redirect_to(Walkthrough.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved walkthrough as @walkthrough" do
        # Trigger the behavior that occurs when invalid params are submitted
        Walkthrough.any_instance.stub(:save).and_return(false)
        post :create, {:walkthrough => { "description" => "invalid value" }}, valid_session
        assigns(:walkthrough).should be_a_new(Walkthrough)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Walkthrough.any_instance.stub(:save).and_return(false)
        post :create, {:walkthrough => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested walkthrough" do
        walkthrough = Walkthrough.create! valid_attributes
        # Assuming there are no other walkthroughs in the database, this
        # specifies that the Walkthrough created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Walkthrough.any_instance.should_receive(:update).with({ "description" => "MyString" })
        put :update, {:id => walkthrough.to_param, :walkthrough => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested walkthrough as @walkthrough" do
        walkthrough = Walkthrough.create! valid_attributes
        put :update, {:id => walkthrough.to_param, :walkthrough => valid_attributes}, valid_session
        assigns(:walkthrough).should eq(walkthrough)
      end

      it "redirects to the walkthrough" do
        walkthrough = Walkthrough.create! valid_attributes
        put :update, {:id => walkthrough.to_param, :walkthrough => valid_attributes}, valid_session
        response.should redirect_to(walkthrough)
      end
    end

    describe "with invalid params" do
      it "assigns the walkthrough as @walkthrough" do
        walkthrough = Walkthrough.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Walkthrough.any_instance.stub(:save).and_return(false)
        put :update, {:id => walkthrough.to_param, :walkthrough => { "description" => "invalid value" }}, valid_session
        assigns(:walkthrough).should eq(walkthrough)
      end

      it "re-renders the 'edit' template" do
        walkthrough = Walkthrough.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Walkthrough.any_instance.stub(:save).and_return(false)
        put :update, {:id => walkthrough.to_param, :walkthrough => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested walkthrough" do
      walkthrough = Walkthrough.create! valid_attributes
      expect {
        delete :destroy, {:id => walkthrough.to_param}, valid_session
      }.to change(Walkthrough, :count).by(-1)
    end

    it "redirects to the walkthroughs list" do
      walkthrough = Walkthrough.create! valid_attributes
      delete :destroy, {:id => walkthrough.to_param}, valid_session
      response.should redirect_to(walkthroughs_url)
    end
  end

end
